# Generated by Django 6.0.7 on 2026-07-25 16:52

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admin_user(apps, schema_editor):

    User = apps.get_model("auth", "User")

    if not User.objects.filter(username="admin").exists():

        User.objects.create(
            username="admin",
            email="admin@example.com",
            password=make_password("admin"),
            is_superuser=True,
            is_staff=True,
            is_active=True
        )


def remove_admin_user(apps, schema_editor):

    User = apps.get_model("auth", "User")

    User.objects.filter(username="admin").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(
            create_admin_user,
            remove_admin_user
        ),
    ]
